on:
  workflow_dispatch:
jobs:
  my_job:
    name: mac-build
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Install tools
      run: brew install nasm x86_64-elf-binutils aarch64-elf-binutils riscv64-elf-binutils
    - name: x86 build
      run: make -j`sysctl -n hw.ncpu` kernel PLATFORM=pc Q=
    - name: ARM build
      run: make -j`sysctl -n hw.ncpu` kernel PLATFORM=virt Q=
    - name: RiscV build
      run: make -j`sysctl -n hw.ncpu` kernel PLATFORM=riscv-virt Q=
